use super::*;
use crate::{AlignmentMode, SeqAlignOptions, SeqAlignment, align_seqs};
use std::collections::BTreeMap;
use std::sync::LazyLock;

/// Species available in the bundled germline reference snapshot.
#[derive(Clone, Copy, Debug, Eq, PartialEq, clap::ValueEnum)]
pub enum GermlineSpecies {
    /// Human H/K/L references.
    Human,
    /// Mouse H/K/L references, including strains and subspecies.
    Mouse,
    /// Alpaca heavy-chain/VHH references.
    Alpaca,
    /// Rat H/K/L references, including strains.
    Rat,
    /// Rabbit H/K/L references, including strains.
    Rabbit,
}

/// Source metadata for a bundled gene/allele reference.
#[derive(Clone, Debug, Serialize)]
#[cfg_attr(
    feature = "python",
    pyo3::pyclass(frozen, get_all, skip_from_py_object, module = "arpeggia")
)]
pub struct GermlineReference {
    /// Stable reference selector: accession, gene/allele, species and source span.
    pub id: String,
    /// Full source species name, including any strain/subspecies suffix.
    pub species: String,
    /// Gene name without allele suffix.
    pub gene: String,
    /// Allele suffix.
    pub allele: String,
    /// Source sequence accession.
    pub accession: String,
}

/// One qualifying sequence alignment, possibly shared by identical references.
#[derive(Clone, Debug, Serialize)]
#[cfg_attr(
    feature = "python",
    pyo3::pyclass(frozen, get_all, skip_from_py_object, module = "arpeggia")
)]
pub struct GermlineHit {
    /// All references sharing this sequence and coverage, sorted by source identity.
    pub references: Vec<GermlineReference>,
    /// Optimal local reference-to-input alignment with BLOSUM62 and gap costs 10/0.5.
    pub alignment: SeqAlignment,
    /// Input index corresponding to query index zero in the segment alignment.
    pub query_input_start: usize,
    /// Internal IMGT positions per reference residue. J junction residues have none.
    pub imgt_positions: Vec<Option<NumberedPosition>>,
    /// One-based, half-open span of available IMGT reference coverage.
    pub imgt_span: (u8, u8),
    /// Nongap pairs where both residues are among the 20 standard amino acids.
    pub known_pairs: usize,
    /// Identical standard-amino-acid pairs.
    pub known_matches: usize,
    /// Known pairs in the input's IMGT FR4 (118–128).
    pub known_fr4_pairs: usize,
    /// Known matches divided by known pairs.
    pub known_identity: f64,
    /// Known pairs divided by all standard residues in the reference segment.
    pub reference_coverage: f64,
    /// Known pairs divided by all standard residues in the input segment.
    pub query_coverage: f64,
}

/// Equally best qualifying V or J similarities, retaining exact score ties.
#[derive(Clone, Debug, Serialize)]
#[cfg_attr(
    feature = "python",
    pyo3::pyclass(frozen, get_all, skip_from_py_object, module = "arpeggia")
)]
pub struct GermlineMatch {
    /// Maximum qualifying local alignment score.
    pub score: f64,
    /// Tied sequence/coverage groups; the first is the display representative.
    pub hits: Vec<GermlineHit>,
}

struct ReferenceGroup {
    references: Vec<GermlineReference>,
    species: GermlineSpecies,
    chain: Chain,
    segment: u8,
    sequence: String,
    encoded: Vec<u8>,
    positions: Vec<Option<NumberedPosition>>,
    span: (u8, u8),
}

fn reference_groups() -> Vec<ReferenceGroup> {
    let mut groups = BTreeMap::new();
    // This versioned embedded file is generated by data/germlines/prepare.py and
    // validated below. It is not a parser for arbitrary user FASTA input.
    for record in include_str!("../../data/germlines/imgt-202636-7.fasta")
        .split('>')
        .skip(1)
    {
        let (header, sequence) = record.split_once('\n').unwrap();
        let fields: Vec<_> = header.split('|').collect();
        let gapped = sequence.trim().as_bytes();
        let species = if fields[2].starts_with("Homo sapiens") {
            GermlineSpecies::Human
        } else if fields[2].starts_with("Mus musculus") {
            GermlineSpecies::Mouse
        } else if fields[2].starts_with("Rattus norvegicus") {
            GermlineSpecies::Rat
        } else if fields[2].starts_with("Oryctolagus cuniculus") {
            GermlineSpecies::Rabbit
        } else {
            GermlineSpecies::Alpaca
        };
        let chain = match fields[1].as_bytes()[2] {
            b'H' => Chain::IGH,
            b'K' => Chain::IGK,
            _ => Chain::IGL,
        };
        let segment = fields[1].as_bytes()[3];
        let (sequence, positions, span) = if segment == b'V' {
            let end = gapped.len().min(104);
            let start = gapped[..end].iter().position(|b| *b != b'.').unwrap();
            let positions: Vec<_> = (start..end).filter(|i| gapped[*i] != b'.').collect();
            let sequence: String = positions.iter().map(|i| gapped[*i] as char).collect();
            let positions = positions
                .into_iter()
                .map(|i| {
                    Some(NumberedPosition {
                        number: (i + 1) as u8,
                        insertion: None,
                    })
                })
                .collect();
            (sequence, positions, ((start + 1) as u8, (end + 1) as u8))
        } else {
            // IMGT FR4 starts at conserved J W/F118. Use the observed motif,
            // not a fixed suffix length: the alpaca IGHJ5 reference ends short.
            let conserved = if chain == Chain::IGH { b'W' } else { b'F' };
            let start = gapped
                .windows(2)
                .rposition(|p| p == [conserved, b'G'])
                .expect("bundled J reference has FR4 W/F-G motif");
            let positions = (0..gapped.len())
                .map(|i| {
                    (i >= start).then(|| NumberedPosition {
                        number: (118 + i - start) as u8,
                        insertion: None,
                    })
                })
                .collect();
            (
                String::from_utf8(gapped.to_vec()).unwrap(),
                positions,
                (118, (118 + gapped.len() - start) as u8),
            )
        };
        let coverage = if segment == b'V' {
            &gapped[..gapped.len().min(104)]
        } else {
            gapped
        };
        let key = (
            fields[1][..4].to_owned(),
            fields[2].to_owned(),
            coverage.to_vec(),
        );
        let group = groups.entry(key).or_insert_with(|| ReferenceGroup {
            references: Vec::new(),
            species,
            chain,
            segment,
            encoded: crate::seq_alignment::encode(&sequence)
                .expect("validated bundled reference alphabet"),
            sequence,
            positions,
            span,
        });
        let (gene, allele) = fields[1].split_once('*').unwrap();
        group.references.push(GermlineReference {
            id: format!("{}|{}|{}|{}", fields[0], fields[1], fields[2], fields[5]),
            species: fields[2].into(),
            gene: gene.into(),
            allele: allele.into(),
            accession: fields[0].into(),
        });
    }
    let mut groups: Vec<_> = groups.into_values().collect();
    for group in &mut groups {
        group.references.sort_by(|a, b| {
            (&a.species, &a.gene, &a.allele, &a.id).cmp(&(&b.species, &b.gene, &b.allele, &b.id))
        });
    }
    groups
}

pub(super) fn known(residue: u8) -> bool {
    b"ACDEFGHIKLMNPQRSTVWY".contains(&residue)
}

pub(super) fn matches(
    antibody: &mut NumberedAntibody,
    raw: &immunum::Alignment,
    chain: Chain,
    species: &[GermlineSpecies],
) -> ArpeggiaResult<()> {
    static REFERENCES: LazyLock<Vec<ReferenceGroup>> = LazyLock::new(reference_groups);
    let imgt = core::convert(raw, Scheme::IMGT, chain, antibody.input_sequence.len())?;
    let start = raw.query_start;
    let split = start + imgt.partition_point(|p| p.number <= 104);
    let end = start + imgt.len();
    let options = SeqAlignOptions {
        mode: AlignmentMode::Local,
        ..Default::default()
    };
    let scoring = crate::seq_alignment::scoring(&options)?;
    let mut scratch = hyalite::PairScratch::new();
    for (segment, window) in [(b'V', start..split), (b'J', split..end)] {
        let query = &antibody.input_sequence[window.clone()];
        let query_known = query.bytes().filter(|b| known(*b)).count();
        let mut result: Option<GermlineMatch> = None;
        let encoded = crate::seq_alignment::encode(query)?;
        let mut ranked = REFERENCES
            .iter()
            .filter(|r| {
                r.chain == chain
                    && r.segment == segment
                    && (species.is_empty() || species.contains(&r.species))
            })
            .map(|group| {
                hyalite::align_pair_with(
                    &mut scratch,
                    &group.encoded,
                    &encoded,
                    &scoring,
                    hyalite::Mode::Sw,
                    hyalite::SearchType::Score,
                )
                .map(|hit| (hit.score, group))
                .map_err(crate::seq_alignment::backend_error)
            })
            .collect::<ArpeggiaResult<Vec<_>>>()?;
        ranked.sort_by_key(|(score, _)| std::cmp::Reverse(*score));
        // Score all candidates with reusable upstream scratch, then construct
        // tracebacks only until the best qualifying score and all its ties are
        // resolved. A high-scoring short/ambiguous match may fail coverage.
        for (score, group) in ranked {
            if result
                .as_ref()
                .is_some_and(|best| f64::from(score) / 100.0 < best.score)
            {
                break;
            }
            let mut alignment = align_seqs(&group.sequence, query, &options)?.value;
            let mut paired = 0;
            let mut identical = 0;
            let mut fr4 = 0;
            for (reference, query_index) in alignment.columns() {
                if let (Some(r), Some(q)) = (reference, query_index) {
                    let (a, b) = (group.sequence.as_bytes()[r], query.as_bytes()[q]);
                    if known(a) && known(b) {
                        paired += 1;
                        identical += usize::from(a == b);
                        fr4 += usize::from(
                            imgt[window.start - start + q].number >= 118
                                && group.positions[r].is_some_and(|p| p.number >= 118),
                        );
                    }
                }
            }
            if (segment == b'V' && paired < 50) || (segment == b'J' && fr4 < 5) {
                continue;
            }
            alignment.reference_name = format!(
                "{}*{}",
                group.references[0].gene, group.references[0].allele
            );
            alignment.query_name = antibody.name.clone();
            let score = alignment.score;
            let hit = GermlineHit {
                references: group.references.clone(),
                alignment,
                query_input_start: window.start,
                imgt_positions: group.positions.clone(),
                imgt_span: group.span,
                known_pairs: paired,
                known_matches: identical,
                known_fr4_pairs: fr4,
                known_identity: identical as f64 / paired as f64,
                reference_coverage: paired as f64
                    / group.sequence.bytes().filter(|b| known(*b)).count() as f64,
                query_coverage: paired as f64 / query_known as f64,
            };
            result
                .get_or_insert_with(|| GermlineMatch {
                    score,
                    hits: Vec::new(),
                })
                .hits
                .push(hit);
        }
        if let Some(result) = &mut result {
            result.hits.sort_by(|a, b| {
                let (a, b) = (&a.references[0], &b.references[0]);
                (&a.species, &a.gene, &a.allele, &a.id)
                    .cmp(&(&b.species, &b.gene, &b.allele, &b.id))
            });
        } else {
            antibody.diagnostics.push(format!(
                "NO_{}_MATCH: insufficient known paired residues in the selected reference species",
                segment as char
            ));
        }
        if segment == b'V' {
            antibody.v_match = result;
        } else {
            antibody.j_match = result;
        }
    }
    Ok(())
}

pub(super) fn reference_positions(
    hit: &GermlineHit,
    scheme: Scheme,
    chain: Chain,
) -> ArpeggiaResult<Vec<Option<NumberedPosition>>> {
    if scheme == Scheme::IMGT {
        return Ok(hit.imgt_positions.clone());
    }
    let source: Vec<_> = hit
        .imgt_positions
        .iter()
        .enumerate()
        .filter_map(|(i, p)| p.map(|p| (i, immunum::alignment::AlignedPosition::Aligned(p.number))))
        .collect();
    let states: Vec<_> = source.iter().map(|(_, p)| *p).collect();
    let converted = core::convert_states(&states, scheme, chain)?;
    let mut result = vec![None; hit.imgt_positions.len()];
    for ((i, _), p) in source.into_iter().zip(converted) {
        result[i] = Some(p);
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_bundle_preserves_sources_and_missing_coverage() {
        let groups = reference_groups();
        assert_eq!(
            groups.iter().map(|g| g.references.len()).sum::<usize>(),
            1694
        );
        assert_eq!(
            groups
                .iter()
                .filter(|g| g.segment == b'J')
                .map(|g| g.references.len())
                .sum::<usize>(),
            91
        );
        assert!(groups.iter().any(|g| g.span.0 > 1 && g.segment == b'V'));
        assert!(
            groups.iter().any(|g| g.species == GermlineSpecies::Mouse
                && g.references[0].species != "Mus musculus")
        );
        assert!(
            groups
                .iter()
                .filter(|g| g.species == GermlineSpecies::Alpaca)
                .all(|g| g.chain == Chain::IGH)
        );
        assert!(
            groups
                .iter()
                .any(|g| g.references.len() >= 3 && g.references[0].gene == "IGHJ4")
        );
        assert!(
            groups
                .iter()
                .filter(|g| g.segment == b'J')
                .all(|g| g.span.1 <= 129)
        );
        assert!(
            groups.iter().any(|g| g.species == GermlineSpecies::Alpaca
                && g.segment == b'J'
                && g.span.1 == 128)
        );
        for (species, prefix, expected) in [
            (GermlineSpecies::Rat, "Rattus norvegicus", 281),
            (GermlineSpecies::Rabbit, "Oryctolagus cuniculus", 143),
        ] {
            let references: Vec<_> = groups
                .iter()
                .filter(|g| g.species == species)
                .flat_map(|g| &g.references)
                .collect();
            assert_eq!(references.len(), expected);
            assert!(references.iter().all(|r| r.species.starts_with(prefix)));
            assert!(references.iter().any(|r| r.species != prefix));
        }
    }

    #[test]
    fn rat_and_rabbit_matches_support_all_chain_classes_and_terminal_imputation() {
        let groups = reference_groups();
        for (species, prefix) in [
            (GermlineSpecies::Rat, "Rattus norvegicus"),
            (GermlineSpecies::Rabbit, "Oryctolagus cuniculus"),
        ] {
            for chain in [Chain::IGH, Chain::IGK, Chain::IGL] {
                let v = groups
                    .iter()
                    .find(|g| {
                        g.species == species
                            && g.chain == chain
                            && g.segment == b'V'
                            && g.span == (1, 105)
                            && g.sequence.bytes().all(known)
                    })
                    .unwrap();
                let j = groups
                    .iter()
                    .find(|g| {
                        g.species == species
                            && g.chain == chain
                            && g.segment == b'J'
                            && g.span.1 >= 128
                            && g.sequence.bytes().all(known)
                    })
                    .unwrap();
                // Synthetic V/junction/J inputs exercise data plumbing, not species accuracy.
                let sequence = format!("{}ARGGG{}", v.sequence, j.sequence);
                for scheme in [
                    NumberingScheme::Imgt,
                    NumberingScheme::Martin,
                    NumberingScheme::Aho,
                    NumberingScheme::Kabat,
                ] {
                    let options = NumberingOptions {
                        species: vec![species],
                        scheme: Some(scheme),
                        ..Default::default()
                    };
                    let full = number_antibody(&sequence, &options).unwrap();
                    assert_eq!(full.chain, chain.to_string());
                    for (matching, source) in [(&full.v_match, v), (&full.j_match, j)] {
                        let matching = matching.as_ref().unwrap();
                        assert!(matching.hits.iter().all(|h| h.known_identity == 1.0));
                        assert!(
                            matching
                                .hits
                                .iter()
                                .flat_map(|h| &h.references)
                                .any(|r| r.id == source.references[0].id)
                        );
                        assert!(
                            matching
                                .hits
                                .iter()
                                .flat_map(|h| &h.references)
                                .all(|r| r.species.starts_with(prefix))
                        );
                    }
                    let partial =
                        number_antibody(&sequence[5..sequence.len() - 3], &options).unwrap();
                    let filled = partial
                        .impute(Some(&v.references[0].id), Some(&j.references[0].id))
                        .unwrap();
                    assert!(filled.residues.len() > partial.residues.len());
                    assert!(
                        filled
                            .residues
                            .iter()
                            .filter(|r| r.input_index.is_none())
                            .all(|r| ["FR1", "FR4"].contains(&r.region.as_str())
                                && !r.imputed_from.is_empty())
                    );
                    assert_eq!(
                        filled
                            .residues
                            .iter()
                            .filter(|r| r.input_index.is_some())
                            .map(|r| (r.position, r.amino_acid, r.input_index))
                            .collect::<Vec<_>>(),
                        partial
                            .residues
                            .iter()
                            .map(|r| (r.position, r.amino_acid, r.input_index))
                            .collect::<Vec<_>>()
                    );
                }
            }
        }
    }

    #[test]
    fn germline_matching_retains_ties_and_qualifies_known_evidence() {
        let groups = reference_groups();
        let v = groups
            .iter()
            .find(|g| {
                g.references
                    .iter()
                    .any(|r| r.gene == "IGHV1-2" && r.allele == "01")
            })
            .unwrap();
        let j = groups
            .iter()
            .find(|g| {
                g.references
                    .iter()
                    .any(|r| r.gene == "IGHJ4" && r.allele == "01")
            })
            .unwrap();
        let sequence = format!("{}ARGGG{}", v.sequence, j.sequence);
        let result = number_antibody(
            &sequence,
            &NumberingOptions {
                species: vec![GermlineSpecies::Human],
                ..Default::default()
            },
        )
        .unwrap();
        let v = result.v_match.as_ref().unwrap();
        assert_eq!(v.hits[0].known_identity, 1.0);
        assert!(
            v.hits
                .iter()
                .flat_map(|h| &h.references)
                .all(|r| r.species.starts_with("Homo sapiens"))
        );
        let j = result.j_match.as_ref().unwrap();
        assert!(
            j.hits
                .iter()
                .flat_map(|h| &h.references)
                .filter(|r| r.gene == "IGHJ4")
                .count()
                >= 3
        );
        assert!(j.hits.iter().all(|h| h.known_fr4_pairs >= 5));
        let kappa = "DIQMTQSPSSLSASVGDRVTITCRASQSISSYLNWYQQKPGKAPKLLIYAASSLQSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQSYSTPPTFGQGTKVEIK";
        let missing = number_antibody(
            kappa,
            &NumberingOptions {
                species: vec![GermlineSpecies::Alpaca],
                ..Default::default()
            },
        )
        .unwrap();
        assert!(missing.v_match.is_none() && missing.j_match.is_none());
        assert!(missing.germlines_searched);
        assert!(missing.impute(None, None).is_ok());
        assert_eq!(missing.diagnostics.len(), 2);
    }
}
