//! Spatial Aggregation Propensity (SAP) score calculations.
//!
//! This module provides functions for calculating SAP scores, which predict
//! aggregation-prone regions in proteins based on hydrophobic surface patches.
//!
//! The SAP score was developed by Chennamsetty et al. and is defined in:
//! "Developability Index: A Rapid In Silico Tool for the Screening of
//! Antibody Aggregation Propensity" (J Pharm Sci, 2012).
//!
//! The formula is:
//! SAP(i) = Σ{j ∈ neighbors(i, R)} [ Hydrophobicity(j) × (SASA(j) / SASA_max(j)) ]
//!
//! Where:
//! - Neighbors are atoms within radius R of atom i
//! - Hydrophobicity uses Rosetta's Black & Mould-derived constants
//! - SASA is the side-chain solvent accessible surface area
//! - SASA_max is the maximum SASA for that residue type

use crate::sasa::{calculate_prepared_sap_atom_sasa_records, validate_sasa_input};
use crate::structure::prepare_structure;
use crate::utils::string_values;
use pdbtbx::*;
use polars::prelude::*;
use rstar::{RTree, primitives::GeomWithData};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Debug)]
struct AtomSapRecord {
    chain: String,
    resn: String,
    resi: i32,
    insertion: String,
    atomn: String,
    atomi: u32,
    sasa: f32,
    sap_score: f32,
}

#[derive(Clone, Debug)]
struct ResidueSapRecord {
    chain: String,
    resn: String,
    resi: i32,
    insertion: String,
    sc_sasa: f32,
    sap_score: f32,
    max_sc_asa: f32,
    relative_sc_sasa: f32,
}

struct SapAtom {
    record: AtomSapRecord,
    position: [f64; 3],
    contribution: f32,
}

/// Black & Mould (1991) hydrophobicity scale values for amino acids.
/// These values are normalized so that the scale ranges from 0 to 1,
/// with Arginine being least hydrophobic (0.0) and Phenylalanine most hydrophobic (1.0).
///
/// Rosetta stores this scale relative to 0.5, leaving glycine at 0.001.
/// Hydrophobic residues have positive values and hydrophilic residues have negative values.
///
/// Original Black & Mould values (0-1 normalized):
/// - PHE: 1.000, ILE: 0.943, LEU: 0.943, TYR: 0.880, TRP: 0.878, VAL: 0.825
/// - MET: 0.738, PRO: 0.711, CYS: 0.680, ALA: 0.616
/// - GLY: 0.501, THR: 0.450, SER: 0.359, LYS: 0.283
/// - GLN: 0.251, ASN: 0.236, HIS: 0.165, GLU: 0.043
/// - ASP: 0.028, ARG: 0.000
///
fn get_hydrophobicity(resn: &str) -> Option<f32> {
    Some(match canonical_sap_residue(resn)? {
        "ALA" => 0.116,
        "ARG" => -0.500,
        "ASN" => -0.264,
        "ASP" => -0.472,
        "CYS" => 0.180,
        "GLN" => -0.249,
        "GLU" => -0.457,
        "GLY" => 0.001,
        "HIS" => -0.335,
        "ILE" | "LEU" => 0.443,
        "LYS" => -0.217,
        "MET" => 0.238,
        "PHE" => 0.500,
        "PRO" => 0.211,
        "SER" => -0.141,
        "THR" => -0.050,
        "TRP" => 0.378,
        "TYR" => 0.380,
        "VAL" => 0.325,
        _ => unreachable!(),
    })
}

/// Get the maximum side-chain solvent accessible surface area (SASA).
///
/// These values are produced by Rosetta's `SapDatabase::generate_max_sasa()`
/// and represent the maximum full-atom side-chain SASA for each residue.
///
/// Returns the maximum side-chain SASA in Å² for a given 3-letter amino acid code,
/// or None if the residue is not a standard amino acid.
fn get_sc_max_asa(resn: &str) -> Option<f32> {
    // Generated by Rosetta's SapDatabase::generate_max_sasa().
    Some(match canonical_sap_residue(resn)? {
        "ALA" => 52.342_068,
        "ARG" => 170.430_51,
        "ASN" => 104.330_7,
        "ASP" => 83.842_09,
        "CYS" => 81.805_786,
        "GLN" => 124.870_65,
        "GLU" => 120.095_19,
        "GLY" => 0.0,
        "HIS" => 131.226_61,
        "ILE" => 135.597_52,
        "LEU" => 133.754_7,
        "LYS" => 161.418_81,
        "MET" => 133.666_67,
        "PHE" => 136.542_05,
        "PRO" => 84.366_356,
        "SER" => 66.747_58,
        "THR" => 83.251_59,
        "TRP" => 165.838_12,
        "TYR" => 162.805_04,
        "VAL" => 108.051_186,
        _ => unreachable!(),
    })
}

fn canonical_sap_residue(resn: &str) -> Option<&str> {
    Some(match resn {
        "ALA" | "ARG" | "ASN" | "ASP" | "CYS" | "GLN" | "GLU" | "GLY" | "ILE" | "LEU" | "LYS"
        | "PHE" | "PRO" | "SER" | "THR" | "TRP" | "TYR" | "VAL" => resn,
        "HIS" | "HID" | "HIE" | "HIP" | "HSD" | "HSE" | "HSP" => "HIS",
        "MET" | "MSE" => "MET",
        _ => return None,
    })
}

fn is_sap_sidechain(resn: &str, atomn: &str) -> bool {
    canonical_sap_residue(resn).is_some()
        && !matches!(
            atomn,
            "N" | "CA"
                | "C"
                | "O"
                | "OXT"
                | "H"
                | "1H"
                | "2H"
                | "3H"
                | "H1"
                | "H2"
                | "H3"
                | "HA"
                | "1HA"
                | "2HA"
                | "HA2"
                | "HA3"
        )
}

/// Calculate the SAP score for each atom in a PDB structure.
///
/// The SAP score quantifies the aggregation propensity by combining the
/// solvent-accessible hydrophobic surface area of neighboring residues.
///
/// # Arguments
///
/// * `pdb` - Reference to a PDB structure
/// * `probe_radius` - Probe radius in Ångströms for SASA calculation (typically 1.1)
/// * `n_points` - Number of points for surface calculation (typically 100)
/// * `model_num` - Model number to analyze (0 for first model)
/// * `sap_radius` - Radius in Ångströms for neighbor search (typically 5.0)
/// * `chains` - Comma-separated chain IDs to include (e.g., "A,B,C"). Empty string includes all chains.
///
/// # Returns
///
/// A Polars `DataFrame` with columns:
/// - `chain`, `resn`, `resi`, `insertion`, `atomn`, `atomi`, `sasa`, `sap_score`
///
/// # Example
///
/// ```no_run
/// use arpeggia::{load_model, get_per_atom_sap_score};
///
/// let input_file = "path/to/structure.pdb".to_string();
/// let pdb = load_model(&input_file).unwrap().value;
///
/// // Calculate SAP for all chains
/// let sap_df = get_per_atom_sap_score(&pdb, 1.1, 100, 0, 5.0, "").unwrap().value;
/// println!("Calculated SAP score for {} atoms", sap_df.height());
///
/// // Calculate SAP for only chains H and L (antibody heavy and light chain)
/// let sap_hl = get_per_atom_sap_score(&pdb, 1.1, 100, 0, 5.0, "H,L").unwrap().value;
/// ```
pub fn get_per_atom_sap_score(
    pdb: &PDB,
    probe_radius: f32,
    n_points: usize,
    model_num: usize,
    sap_radius: f32,
    chains: &str,
) -> crate::ArpeggiaResult<crate::Analysis<DataFrame>> {
    if !sap_radius.is_finite() || sap_radius <= 0.0 {
        return Err(crate::ArpeggiaError::InvalidArgument(
            "sap_radius must be finite and positive".into(),
        ));
    }
    validate_sasa_input(pdb, probe_radius, n_points, model_num, chains)?;
    let analysis = prepare_structure(pdb, model_num, false, chains);
    let (records, unsupported) =
        calculate_per_atom_sap_records(&analysis.value, probe_radius, n_points, sap_radius)?;
    let mut warnings = analysis.warnings;
    append_unsupported_monomer_warning(&unsupported, &mut warnings);
    append_prepared_input_warnings(&analysis.value, &mut warnings);
    Ok(crate::Analysis::new(
        atom_sap_records_to_dataframe(&records),
        warnings,
    ))
}

fn calculate_per_atom_sap_records(
    pdb: &PDB,
    probe_radius: f32,
    n_points: usize,
    sap_radius: f32,
) -> crate::ArpeggiaResult<(Vec<AtomSapRecord>, BTreeSet<String>)> {
    // SAP applies Rosetta's Reduce-radius exposure definition to all supplied
    // atoms; standard SASA remains a separate heavy-atom ProtOr calculation.
    let atom_sasa_records = calculate_prepared_sap_atom_sasa_records(pdb, probe_radius, n_points)?;
    let unsupported = atom_sasa_records
        .iter()
        .filter(|record| {
            get_hydrophobicity(&record.resn).is_none() || get_sc_max_asa(&record.resn).is_none()
        })
        .map(|record| record.resn.clone())
        .collect::<BTreeSet<_>>();
    // [WARNING] Rosetta publishes no SAP calibration for these monomers. They
    // are omitted and diagnosed instead of borrowing an unjustified constant.
    let atoms = atom_sasa_records
        .into_iter()
        .zip(pdb.atoms_with_hierarchy())
        .filter(|(record, _)| {
            !unsupported.contains(&record.resn) && is_sap_sidechain(&record.resn, &record.atomn)
        })
        .filter_map(|(record, entity)| {
            debug_assert_eq!(record.atomi as usize, entity.atom().serial_number());
            let hydrophobicity = get_hydrophobicity(&record.resn)?;
            let max_asa = get_sc_max_asa(&record.resn)?;
            let position = entity.atom().pos();
            Some(SapAtom {
                contribution: if max_asa == 0.0 {
                    0.0
                } else {
                    hydrophobicity * record.sasa / max_asa
                },
                position: [position.0, position.1, position.2],
                record: AtomSapRecord {
                    chain: record.chain,
                    resn: record.resn,
                    resi: record.resi,
                    insertion: record.insertion,
                    atomn: record.atomn,
                    atomi: record.atomi,
                    sasa: record.sasa,
                    sap_score: 0.0,
                },
            })
        })
        .collect::<Vec<_>>();
    let tree = RTree::bulk_load(
        atoms
            .iter()
            .enumerate()
            .map(|(index, atom)| GeomWithData::new(atom.position, index))
            .collect(),
    );
    let sap_radius_sq = f64::from(sap_radius * sap_radius);
    let scores = atoms
        .iter()
        .map(|atom| {
            tree.locate_within_distance(atom.position, sap_radius_sq)
                .filter(|neighbor| {
                    let position = atoms[neighbor.data].position;
                    atom.position
                        .iter()
                        .zip(position)
                        .map(|(left, right)| (left - right).powi(2))
                        .sum::<f64>()
                        < sap_radius_sq
                })
                .map(|neighbor| atoms[neighbor.data].contribution)
                .sum::<f32>()
        })
        .collect::<Vec<_>>();
    let mut records = atoms
        .into_iter()
        .zip(scores)
        .map(|(atom, sap_score)| AtomSapRecord {
            sap_score,
            ..atom.record
        })
        .collect::<Vec<_>>();
    records.sort_by_key(|record| record.atomi);
    Ok((records, unsupported))
}

fn append_unsupported_monomer_warning(
    unsupported: &BTreeSet<String>,
    warnings: &mut Vec<crate::AnalysisWarning>,
) {
    if !unsupported.is_empty() {
        warnings.push(crate::AnalysisWarning::new(
            crate::WarningCode::UnsupportedMonomer,
            format!(
                "SAP omitted monomers without Rosetta calibration: {}",
                unsupported.iter().cloned().collect::<Vec<_>>().join(", ")
            ),
        ));
    }
}

fn append_prepared_input_warnings(pdb: &PDB, warnings: &mut Vec<crate::AnalysisWarning>) {
    let Some(model) = pdb.models().next() else {
        return;
    };
    let selected_chains = model.chains().collect::<Vec<_>>();
    if selected_chains
        .iter()
        .flat_map(|chain| chain.atoms())
        .all(|atom| atom.element() != Some(&Element::H))
    {
        warnings.push(crate::AnalysisWarning::new(
            crate::WarningCode::HydrogenFreeInput,
            "SAP numerical compatibility requires a caller-prepared full-atom structure, but the selected input contains no hydrogens",
        ));
    }

    let mut unresolved = 0;
    let mut inconsistent = 0;
    for residue in selected_chains.iter().flat_map(|chain| chain.residues()) {
        match crate::contacts::ionic::histidine_preparation_issue(residue) {
            Some(crate::contacts::ionic::HistidinePreparationIssue::Unresolved) => unresolved += 1,
            Some(crate::contacts::ionic::HistidinePreparationIssue::Inconsistent) => {
                inconsistent += 1;
            }
            None => {}
        }
    }
    if unresolved > 0 {
        warnings.push(crate::AnalysisWarning::new(
            crate::WarningCode::UnresolvedHistidine,
            format!(
                "{unresolved} histidine residues have no explicit tautomer or ring-hydrogen evidence"
            ),
        ));
    }
    if inconsistent > 0 {
        warnings.push(crate::AnalysisWarning::new(
            crate::WarningCode::InconsistentHistidine,
            format!(
                "{inconsistent} histidine residues have names inconsistent with their explicit ring hydrogens"
            ),
        ));
    }
}

fn atom_sap_records_to_dataframe(records: &[AtomSapRecord]) -> DataFrame {
    df!(
        "chain" => string_values(records.iter().map(|record| record.chain.as_str())),
        "resn" => string_values(records.iter().map(|record| record.resn.as_str())),
        "resi" => records.iter().map(|record| record.resi).collect::<Vec<_>>(),
        "insertion" => string_values(records.iter().map(|record| record.insertion.as_str())),
        "atomn" => string_values(records.iter().map(|record| record.atomn.as_str())),
        "atomi" => records.iter().map(|record| record.atomi).collect::<Vec<_>>(),
        "sasa" => records.iter().map(|record| record.sasa).collect::<Vec<_>>(),
        "sap_score" => records.iter().map(|record| record.sap_score).collect::<Vec<_>>(),
    )
    .unwrap()
    .sort(["atomi"], Default::default())
    .unwrap()
}

/// Calculate the SAP score aggregated by residue.
///
/// The per-residue SAP score is calculated by summing the per-atom SAP scores
/// for all atoms in each residue, weighted by their SASA contribution.
///
/// # Arguments
///
/// * `pdb` - Reference to a PDB structure
/// * `probe_radius` - Probe radius in Ångströms for SASA calculation (typically 1.1)
/// * `n_points` - Number of points for surface calculation (typically 100)
/// * `model_num` - Model number to analyze (0 for first model)
/// * `sap_radius` - Radius in Ångströms for neighbor search (typically 5.0)
/// * `chains` - Comma-separated chain IDs to include (e.g., "A,B,C"). Empty string includes all chains.
///
/// # Returns
///
/// A Polars `DataFrame` with columns:
/// - `chain`, `resn`, `resi`, `insertion`, `sc_sasa`, `sap_score`
///
/// # Example
///
/// ```no_run
/// use arpeggia::{load_model, get_per_residue_sap_score};
///
/// let input_file = "path/to/structure.pdb".to_string();
/// let pdb = load_model(&input_file).unwrap().value;
///
/// // Calculate SAP for all chains
/// let sap_df = get_per_residue_sap_score(&pdb, 1.1, 100, 0, 5.0, "").unwrap().value;
/// println!("Calculated SAP score for {} residues", sap_df.height());
///
/// // Calculate SAP for only chain A
/// let sap_a = get_per_residue_sap_score(&pdb, 1.1, 100, 0, 5.0, "A").unwrap().value;
/// ```
pub fn get_per_residue_sap_score(
    pdb: &PDB,
    probe_radius: f32,
    n_points: usize,
    model_num: usize,
    sap_radius: f32,
    chains: &str,
) -> crate::ArpeggiaResult<crate::Analysis<DataFrame>> {
    if !sap_radius.is_finite() || sap_radius <= 0.0 {
        return Err(crate::ArpeggiaError::InvalidArgument(
            "sap_radius must be finite and positive".into(),
        ));
    }
    validate_sasa_input(pdb, probe_radius, n_points, model_num, chains)?;
    let analysis = prepare_structure(pdb, model_num, false, chains);
    let (records, unsupported) =
        calculate_per_residue_sap_records(&analysis.value, probe_radius, n_points, sap_radius)?;
    let mut warnings = analysis.warnings;
    append_unsupported_monomer_warning(&unsupported, &mut warnings);
    append_prepared_input_warnings(&analysis.value, &mut warnings);
    Ok(crate::Analysis::new(
        residue_sap_records_to_dataframe(&records),
        warnings,
    ))
}

fn calculate_per_residue_sap_records(
    pdb: &PDB,
    probe_radius: f32,
    n_points: usize,
    sap_radius: f32,
) -> crate::ArpeggiaResult<(Vec<ResidueSapRecord>, BTreeSet<String>)> {
    let mut grouped: BTreeMap<(String, String, i32, String), (f32, f32)> = BTreeMap::new();

    for model in pdb.models() {
        for chain in model.chains() {
            for residue in chain.residues() {
                let Some(resn) = residue
                    .name()
                    .filter(|name| canonical_sap_residue(name).is_some())
                else {
                    continue;
                };
                let resi = i32::try_from(residue.serial_number()).map_err(|_| {
                    crate::ArpeggiaError::Calculation("residue identifier exceeds Int32".into())
                })?;
                grouped.insert(
                    (
                        chain.id().to_string(),
                        resn.to_string(),
                        resi,
                        residue.insertion_code().unwrap_or("").to_string(),
                    ),
                    (0.0, 0.0),
                );
            }
        }
    }

    let (atom_records, unsupported) =
        calculate_per_atom_sap_records(pdb, probe_radius, n_points, sap_radius)?;
    for record in atom_records {
        let key = (record.chain, record.resn, record.resi, record.insertion);
        let (sc_sasa, sap_score) = grouped.entry(key).or_insert((0.0, 0.0));
        *sc_sasa += record.sasa;
        // [ACCEPTED DEVIATION] Match Rosetta's positive-only per-residue SAP
        // accumulation while keeping the complete side-chain SASA above.
        *sap_score += record.sap_score.max(0.0);
    }

    let mut records = grouped
        .into_iter()
        .map(|((chain, resn, resi, insertion), (sc_sasa, sap_score))| {
            let max_sc_asa = get_sc_max_asa(&resn).unwrap();
            ResidueSapRecord {
                chain,
                resn,
                resi,
                insertion,
                sc_sasa,
                sap_score,
                max_sc_asa,
                relative_sc_sasa: if max_sc_asa == 0.0 {
                    0.0
                } else {
                    sc_sasa / max_sc_asa
                },
            }
        })
        .collect::<Vec<_>>();
    records.sort_by(|a, b| (&a.chain, a.resi, &a.insertion).cmp(&(&b.chain, b.resi, &b.insertion)));
    Ok((records, unsupported))
}

fn residue_sap_records_to_dataframe(records: &[ResidueSapRecord]) -> DataFrame {
    df!(
        "chain" => string_values(records.iter().map(|record| record.chain.as_str())),
        "resn" => string_values(records.iter().map(|record| record.resn.as_str())),
        "resi" => records.iter().map(|record| record.resi).collect::<Vec<_>>(),
        "insertion" => string_values(records.iter().map(|record| record.insertion.as_str())),
        "sc_sasa" => records.iter().map(|record| record.sc_sasa).collect::<Vec<_>>(),
        "sap_score" => records.iter().map(|record| record.sap_score).collect::<Vec<_>>(),
        "max_sc_asa" => records.iter().map(|record| record.max_sc_asa).collect::<Vec<_>>(),
        "relative_sc_sasa" => records.iter().map(|record| record.relative_sc_sasa).collect::<Vec<_>>(),
    )
    .unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{WarningCode, load_model, run_with_threads};
    use std::io::BufReader;

    fn load_ubiquitin() -> PDB {
        let root = env!("CARGO_MANIFEST_DIR");
        let path = format!("{}/{}", root, "test-data/1ubq.pdb");
        load_model(&path).unwrap().value
    }

    fn load_multi_chain() -> PDB {
        let root = env!("CARGO_MANIFEST_DIR");
        let path = format!("{}/{}", root, "test-data/6bft.pdb");
        load_model(&path).unwrap().value
    }

    #[test]
    fn test_hydrophobicity_values() {
        assert_eq!(get_hydrophobicity("GLY"), Some(0.001));
        assert_eq!(get_hydrophobicity("PHE"), Some(0.500));
        assert_eq!(get_hydrophobicity("ARG"), Some(-0.500));

        assert!(get_hydrophobicity("XXX").is_none());

        for alias in ["HID", "HIE", "HIP", "HSD", "HSE", "HSP"] {
            assert_eq!(get_hydrophobicity(alias), get_hydrophobicity("HIS"));
            assert_eq!(get_sc_max_asa(alias), get_sc_max_asa("HIS"));
        }
        assert_eq!(get_hydrophobicity("MSE"), get_hydrophobicity("MET"));
        assert_eq!(get_sc_max_asa("MSE"), get_sc_max_asa("MET"));
    }

    #[test]
    fn test_max_asa_values() {
        let amino_acids = [
            "ALA", "ARG", "ASN", "ASP", "CYS", "GLU", "GLN", "GLY", "HIS", "ILE", "LEU", "LYS",
            "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL",
        ];

        for aa in &amino_acids {
            let max_sasa = get_sc_max_asa(aa);
            assert!(max_sasa.is_some(), "Should have max SASA for {aa}");
            assert!(
                max_sasa.unwrap() >= 0.0,
                "Max SASA for {aa} should be nonnegative"
            );
        }

        assert_eq!(get_sc_max_asa("GLY"), Some(0.0));
        assert_eq!(get_sc_max_asa("TRP"), Some(165.838_12));
    }

    #[test]
    fn sap_sidechains_include_hydrogens_and_mse_but_not_oxt() {
        let input =
            b"ATOM      1  CB  ALA A   1       0.000   0.000   0.000  1.00 20.00           C  \n\
ATOM      2  HB1 ALA A   1       1.000   0.000   0.000  1.00 20.00           H  \n\
ATOM      3  OXT ALA A   1       2.000   0.000   0.000  1.00 20.00           O  \n\
END                                                                             \n";
        let (pdb, _) = ReadOptions::default()
            .set_format(Format::Pdb)
            .set_only_atomic_coords(true)
            .read_raw(BufReader::new(input.as_slice()))
            .unwrap();
        let df = get_per_atom_sap_score(&pdb, 1.1, 20, 0, 5.0, "")
            .unwrap()
            .value;
        let names = df
            .column("atomn")
            .unwrap()
            .str()
            .unwrap()
            .iter()
            .flatten()
            .collect::<Vec<_>>();

        assert_eq!(names, ["CB", "HB1"]);
        assert!(is_sap_sidechain("MSE", "SE"));
        assert!(!is_sap_sidechain("GLY", "HA2"));
    }

    #[test]
    fn test_per_atom_sap_returns_data() {
        let pdb = load_ubiquitin();
        let df = run_with_threads(1, || get_per_atom_sap_score(&pdb, 1.4, 100, 0, 5.0, ""));
        let df = df.unwrap().value;

        // Check that we get results
        assert!(df.height() > 0, "SAP DataFrame should not be empty");

        // Check columns
        let columns: Vec<String> = df
            .get_column_names()
            .iter()
            .map(|s| s.to_string())
            .collect();
        assert!(columns.contains(&"chain".to_string()));
        assert!(columns.contains(&"resn".to_string()));
        assert!(columns.contains(&"resi".to_string()));
        assert!(columns.contains(&"atomn".to_string()));
        assert!(columns.contains(&"atomi".to_string()));
        assert!(columns.contains(&"sasa".to_string()));
        assert!(columns.contains(&"sap_score".to_string()));
        assert_eq!(df.column("resi").unwrap().dtype(), &DataType::Int32);
        assert_eq!(df.column("atomi").unwrap().dtype(), &DataType::UInt32);
    }

    #[test]
    fn test_per_atom_sap_values_reasonable() {
        let pdb = load_ubiquitin();
        let df = run_with_threads(1, || get_per_atom_sap_score(&pdb, 1.4, 100, 0, 5.0, ""));
        let df = df.unwrap().value;

        // Get SAP scores
        let sap_values: Vec<f32> = df
            .column("sap_score")
            .unwrap()
            .f32()
            .unwrap()
            .iter()
            .flatten()
            .collect();

        // SAP values should have both positive and negative values
        // (hydrophobic and hydrophilic patches)
        let has_positive = sap_values.iter().any(|&v| v > 0.0);
        let has_negative = sap_values.iter().any(|&v| v < 0.0);

        assert!(has_positive, "Should have some positive SAP scores");
        assert!(has_negative, "Should have some negative SAP scores");
    }

    #[test]
    fn unsupported_sap_monomers_are_omitted_with_a_warning() {
        let input =
            b"ATOM      1  CB  SEC A   1       0.000   0.000   0.000  1.00 20.00           C  \n\
END                                                                             \n";
        let (pdb, _) = ReadOptions::default()
            .set_format(Format::Pdb)
            .set_only_atomic_coords(true)
            .read_raw(BufReader::new(input.as_slice()))
            .unwrap();

        let analysis = get_per_residue_sap_score(&pdb, 1.4, 100, 0, 5.0, "").unwrap();
        assert_eq!(analysis.value.height(), 0);
        assert!(
            analysis
                .warnings
                .iter()
                .any(|warning| warning.code == WarningCode::UnsupportedMonomer)
        );
    }

    #[test]
    fn test_per_residue_sap_returns_data() {
        let pdb = load_ubiquitin();
        let df = run_with_threads(1, || get_per_residue_sap_score(&pdb, 1.4, 100, 0, 5.0, ""));
        let df = df.unwrap().value;

        // Check that we get results
        assert!(df.height() > 0, "Residue SAP DataFrame should not be empty");

        // Check columns
        let columns: Vec<String> = df
            .get_column_names()
            .iter()
            .map(|s| s.to_string())
            .collect();
        assert!(columns.contains(&"chain".to_string()));
        assert!(columns.contains(&"resn".to_string()));
        assert!(columns.contains(&"resi".to_string()));
        assert!(columns.contains(&"sc_sasa".to_string()));
        assert!(columns.contains(&"sap_score".to_string()));
    }

    #[test]
    fn residue_sap_includes_zero_valued_glycines() {
        let pdb = load_ubiquitin();
        let df = run_with_threads(1, || get_per_residue_sap_score(&pdb, 1.1, 100, 0, 5.0, ""))
            .unwrap()
            .value;
        assert_eq!(df.height(), 76);

        let glycine = df
            .filter(&df.column("resn").unwrap().str().unwrap().equal("GLY"))
            .unwrap();
        assert_eq!(glycine.height(), 6);
        for column in ["sc_sasa", "sap_score", "max_sc_asa", "relative_sc_sasa"] {
            assert!(
                glycine
                    .column(column)
                    .unwrap()
                    .f32()
                    .unwrap()
                    .iter()
                    .flatten()
                    .all(|value| value == 0.0),
                "{column} should be zero for GLY"
            );
        }
    }

    #[test]
    fn sap_warns_about_unprepared_full_atom_input() {
        let ubiquitin = get_per_atom_sap_score(&load_ubiquitin(), 1.1, 20, 0, 5.0, "").unwrap();
        assert!(
            ubiquitin
                .warnings
                .iter()
                .any(|warning| warning.code == WarningCode::HydrogenFreeInput)
        );

        let input =
            b"ATOM      1  ND1 HIS A   1       0.000   0.000   0.000  1.00 20.00           N  \n\
ATOM      2  ND1 HID A   2       4.000   0.000   0.000  1.00 20.00           N  \n\
ATOM      3  HE2 HID A   2       5.000   0.000   0.000  1.00 20.00           H  \n\
END                                                                             \n";
        let (pdb, _) = ReadOptions::default()
            .set_format(Format::Pdb)
            .set_only_atomic_coords(true)
            .read_raw(BufReader::new(input.as_slice()))
            .unwrap();
        let analysis = get_per_atom_sap_score(&pdb, 1.1, 20, 0, 5.0, "").unwrap();
        assert!(
            analysis
                .warnings
                .iter()
                .any(|warning| warning.code == WarningCode::UnresolvedHistidine)
        );
        assert!(
            analysis
                .warnings
                .iter()
                .any(|warning| warning.code == WarningCode::InconsistentHistidine)
        );
    }

    #[test]
    fn residue_sap_keeps_complete_sidechain_sasa() {
        let pdb = load_ubiquitin();
        let atom = run_with_threads(1, || get_per_atom_sap_score(&pdb, 1.4, 100, 0, 5.0, ""));
        let atom = atom.unwrap().value;
        let residue = run_with_threads(1, || get_per_residue_sap_score(&pdb, 1.4, 100, 0, 5.0, ""));
        let residue = residue.unwrap().value;
        let mut expected = BTreeMap::<(String, String, i32, String), (f32, f32)>::new();

        for row in 0..atom.height() {
            let key = (
                atom.column("chain")
                    .unwrap()
                    .str()
                    .unwrap()
                    .get(row)
                    .unwrap()
                    .to_string(),
                atom.column("resn")
                    .unwrap()
                    .str()
                    .unwrap()
                    .get(row)
                    .unwrap()
                    .to_string(),
                atom.column("resi")
                    .unwrap()
                    .i32()
                    .unwrap()
                    .get(row)
                    .unwrap(),
                atom.column("insertion")
                    .unwrap()
                    .str()
                    .unwrap()
                    .get(row)
                    .unwrap()
                    .to_string(),
            );
            let entry = expected.entry(key).or_default();
            entry.0 += atom
                .column("sasa")
                .unwrap()
                .f32()
                .unwrap()
                .get(row)
                .unwrap();
            entry.1 += atom
                .column("sap_score")
                .unwrap()
                .f32()
                .unwrap()
                .get(row)
                .unwrap()
                .max(0.0);
        }

        assert!(residue.height() >= expected.len());
        for row in 0..residue.height() {
            let key = (
                residue
                    .column("chain")
                    .unwrap()
                    .str()
                    .unwrap()
                    .get(row)
                    .unwrap()
                    .to_string(),
                residue
                    .column("resn")
                    .unwrap()
                    .str()
                    .unwrap()
                    .get(row)
                    .unwrap()
                    .to_string(),
                residue
                    .column("resi")
                    .unwrap()
                    .i32()
                    .unwrap()
                    .get(row)
                    .unwrap(),
                residue
                    .column("insertion")
                    .unwrap()
                    .str()
                    .unwrap()
                    .get(row)
                    .unwrap()
                    .to_string(),
            );
            let Some(&(expected_sasa, expected_score)) = expected.get(&key) else {
                assert_eq!(key.1, "GLY");
                continue;
            };
            let actual_sasa = residue
                .column("sc_sasa")
                .unwrap()
                .f32()
                .unwrap()
                .get(row)
                .unwrap();
            let actual_score = residue
                .column("sap_score")
                .unwrap()
                .f32()
                .unwrap()
                .get(row)
                .unwrap();
            assert!(
                (actual_sasa - expected_sasa).abs() < 1e-4,
                "wrong SASA for {key:?}"
            );
            assert!(
                (actual_score - expected_score).abs() < 1e-4,
                "wrong SAP for {key:?}"
            );
        }
    }

    #[test]
    fn sap_exposure_ratio_is_not_silently_clamped() {
        let input =
            b"ATOM      1  CB  ALA A   1       0.000   0.000   0.000  1.00 20.00           C  \n\
END                                                                             \n";
        let pdb = ReadOptions::default()
            .set_format(Format::Pdb)
            .set_only_atomic_coords(true)
            .read_raw(BufReader::new(input.as_slice()))
            .unwrap()
            .0;
        let residue = get_per_residue_sap_score(&pdb, 1.1, 100, 0, 5.0, "")
            .unwrap()
            .value;

        assert!(
            residue
                .column("relative_sc_sasa")
                .unwrap()
                .f32()
                .unwrap()
                .get(0)
                .unwrap()
                > 1.0
        );
        assert!(
            residue
                .column("sap_score")
                .unwrap()
                .f32()
                .unwrap()
                .get(0)
                .unwrap()
                > get_hydrophobicity("ALA").unwrap()
        );
    }

    #[test]
    fn test_sap_multi_chain() {
        let pdb = load_multi_chain();
        let df = run_with_threads(1, || get_per_residue_sap_score(&pdb, 1.4, 100, 0, 5.0, ""));
        let df = df.unwrap().value;

        // Should have results
        assert!(df.height() > 0, "Multi-chain SAP should not be empty");

        // Should have multiple chains
        let chain_count = df.column("chain").unwrap().unique().unwrap().len();
        assert!(
            chain_count > 1,
            "Should have multiple chains: {chain_count}"
        );
    }
}
