name: "pypi"

on:
  release:
    types: [released]
  workflow_dispatch: # manual trigger

jobs:
  # Adapted from pydantic/pydantic-core
  build:
    name: build on ${{ matrix.platform.os }} / ${{ matrix.interpreter }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            { os: linux, runs-on: ubuntu-latest },
            { os: linux_aarch64, runs-on: ubuntu-24.04-arm },
            { os: windows, runs-on: windows-latest },
            { os: macos, runs-on: macos-latest },
          ]
        interpreter: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
        target: [x86_64, aarch64]

        exclude:
          - platform:
              os: linux_aarch64
            target: x86_64
          - platform:
              os: linux
            target: aarch64
          - platform:
              os: windows
            target: aarch64
          - platform:
              os: windows
            interpreter: "3.14t" # not supported
          - platform:
              os: macos
            target: x86_64 # too slow on GitHub runners

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Install uv
        uses: astral-sh/setup-uv@94527f2e458b27549849d47d273a16bec83a01e9 # v7
        with:
          python-version: ${{ matrix.interpreter }}
          ignore-nothing-to-cache: true
          ignore-empty-workdir: true

      - name: Install Rust stable
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          components: llvm-tools
          toolchain: stable

      - name: Build wheels
        uses: PyO3/maturin-action@423a6347767a8b16e65c2a7a7042e4a921528da8 # v1
        with:
          manylinux: auto
          target: ${{ matrix.target }}
          args: >
            --release
            --out dist
            --features python
            --locked
            --interpreter ${{ matrix.interpreter }}
          rust-toolchain: ${{ steps.rust-toolchain.outputs.name }}
          docker-options: -e CI

      - run: ${{ (matrix.platform.os == 'windows' && 'dir') || 'ls -lh' }} dist

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: pypi_files_${{ matrix.platform.os }}_${{ matrix.target }}_${{ matrix.interpreter }}
          path: dist

  publish:
    name: publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@94527f2e458b27549849d47d273a16bec83a01e9 # v7

      - name: get dist artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          pattern: pypi_files_*
          merge-multiple: true
          path: dist

      - name: Publish
        run: uv publish --trusted-publishing always
